### ISSUE TITLE
Response: figure 5

### ISSUE THREAD

**Issue by sammo3182** [fsolt/meritocracy#17] opened 2016-05-19 18:17 UTC
In the memo:
"We have ensured Figure 5 is properly labeled."

Verify by Kevan.

**Comment by dongericoyu** [comment] 2016-06-06 14:23
This has been fixed in the revise memo. Suggested close the issue.

**Comment by kwhudson** [comment] 2016-06-15 02:16
I might suggest that change the wording slightly.

Currently it is:

"Reviewer 1 noted that the axis values and lengend of Figure 5 are missing. After a careful review of the original submission of the paper, we confirmed that Figure 5 is properly labelled. We also attached a separate Figure 5 in this memo; see page XX."

I think that:

Reviewer 1 noted that Figure 5 was difficult to interpret due to missing axis values and legend. After a careful review of the original submission of the paper, we have ensured that Figure 5 is properly labelled. We have also attached a separate Figure 5 in this memo; see page XX.

Works a bit better because it doesn't suggest the reviewer was wrong, just that we made sure the problem is fixed. Otherwise I think this looks good.

@dongericoyu

**Closed as completed** 2016-07-12 16:20 UTC
